#if !canImport(ObjectiveC)
import XCTest

extension SwiftIndexStoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftIndexStoreTests = [
        ("testExample", testExample)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftIndexStoreTests.__allTests__SwiftIndexStoreTests)
    ]
}
#endif
