name: Build and run tests
on:
  push: {}
  pull_request: {}
jobs:
  macos:
    runs-on: macOS-latest
    name: macOS
    steps:
    - uses: actions/checkout@v3
    - name: Xcode version
      run: /usr/bin/xcode-select --print-path
    - name: Build
      run: swift build
    - name: Test
      run: swift test
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        swift-version: ["5.8", "5.9", "5.10"]
    container: swift:${{ matrix.swift-version }}-jammy
    name: Linux
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test
